services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - http.port=9200
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    environment:
      SERVER_NAME: labo-big-data
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"


  logstash:
      user: root
      image: docker.elastic.co/logstash/logstash:8.16.1
      entrypoint: [ "sh", "-c", "sleep 2073600" ]
      depends_on:
        elasticsearch:
          condition: service_healthy
      environment:
        - "xpack.monitoring.enabled=false"
      command: logstash -f pipeline/books.conf --config.reload.automatic
      volumes:
          - ./logstash/pipeline:/usr/share/logstash/pipeline
          - ./logstash/data/:/usr/share/logstash/data/

volumes:
  es: